### ISSUE TITLE
h1~6 的id需要加 hash-

### ISSUE THREAD

**Issue by Grifree** [markrun/markrun#2]
防止 

```
# demo
<div id="demo" ></div>
```
出现的冲突

```
<h1 id="demo" >demo</h1>
<div id="demo" ></div>
```

**Comment by nimojs** [comment]
https://github.com/markrun/markrun/blob/master/lib/marked.js#L9

**Comment by nimojs** [comment]
https://github.com/markrun/markrun/commit/c0476ca6509206aa3ec154814f17a94023d5c71d#dif
f-81ab0a5aa39b7a91951fc28d2d151496L9

最终取消前缀加 hash ，因为要保持与 github一致
